[package]
name = "simple-kv"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = "Uses Redis KV store"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"

[workspace]
