apiVersion: v1
kind: Pod
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  containers:
  - name: emqx
    image: emqx/emqx
    ports:
    - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  selector:
    app: emqx
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
  type: ClusterIP  
