spin_manifest_version = 2

[application]
name = "mqtt-app"
version = "0.1.0"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = "Triggered by MQTT"

[variables]
topic = { required = true }
broker_uri = { required = true }

[application.trigger.mqtt]
# address = "mqtt://localhost:1883"
address = "{{ broker_uri }}"
username = ""
password = ""
keep_alive_interval = "30"

[[trigger.mqtt]]
component = "mqtt-app"
topic = "{{ topic }}"
qos = "1"

[component.mqtt-app]
source = "handle-mqtt/target/wasm32-wasi/release/mqtt_app.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.mqtt-app.build]
command = "cargo build --target wasm32-wasi --release --manifest-path handle-mqtt/Cargo.toml"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/api"
component = "api"

[component.api]
source = "api/target/api.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.api.build]
command = "npm run build"
workdir = "api"

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "frontend/", destination = "/" }]